### PR TITLE
added SSID, BSSID and IBSS

### PR DESCRIPTION
**Pull request by mojoaxel**

### CODE REVIEW

**Comment by mojoaxel** [comment]
Maybe I should add that I'm not shure about the key names. I tried to understand the different name conventions in wireless networks but got confused most oft the time. 
So, if anybody can bring more light in this topic or has better namens in mind, don't hasitate...

**Comment by bittorf** [comment]
ok, i will explain that:
SSID or "ESSID" is the name of the network. this is what you can see i your "network-manager": the name which you want to connect to.

BSSID is only for adhoc = IBSS-networks: the identifier of the 'cell'. it looks like a mac-address, but IS NOT. all routers in the same cell must have the same BSSID configured. in IBSS-networks, each router _can_ have another SSID, only the  BSSID must be the same.

IBSS is another word for 'adhoc'-mode. i think we dont need this here.

**Comment by christian-weiss** [comment]
This PR is very old. Is it still valid or can we close it?

@mojoaxel @bittorf 
Maybe a stupid question: What is the benefit of having SSID, BSSID and IBSS in a API file?
As the API file is for processing by machines, please give me one or two use cases in which these fields would be necessary.

**Comment by mojoaxel** [comment]
@christian-weiss Feel free to close it!

**Pull request closed without merging**
