### PR TITLE
true draft-03 schema files (no wrapper, no "empty schema") + soft migration to draft-07

### LINKED ISSUE #151: Migration von JSON Schema draft-3 zu draft-7
Laut https://json-schema.org/specification.html sind 

- draft-7
- draft-6
- draft-4

derzeit die aktuellen Spezifikationen. Ältere Spezifikationen werden hier gelistet:
https://json-schema.org/specification-links.html
und dort als "**expired**, but may be of historical interest" aufgeführt.

Freifunk setzt bisher **draft-3** ein. Diese Spezifikation ist von 2010. Neuere Validatoren haben keinen Support mehr für diese alten Spezifikationen und ältere Validatoren werden oft nicht mehr gepflegt, womit **Vulnerabilities / Security Issues** wahrscheinlich sind / wahrscheinlicher werden.

Ich rate dazu zusätzliche zu den draft-3 Freifunk JSON Schema Dateien nun auch draft-7 Dateien bereitzustellen, um eine **Soft Migration** zu ermöglichen. Zudem würde ich an bekannte Script- / Client-Entwickler, sowie in forum.freifunk.net und an technische Ansprechpartner in den lokalen Gruppen (E-Mail) eine **DEPRECATION NOTICE** bzgl. draft-3 veröffentlichen, mit der Bitte um **Migration auf draft-7** bis zum **31.12.2019**. 

Zu diesem Zeitpunkt würde ich gerne die draft-3 Dateien aus unserem Repo entfernen, nachdem wir natürlich "geprüft" haben wie gut draft-7 adaptiert wurde. Dieser Vorgang ist nicht disruptiv - eine Soft-Migration.

Mir fallen folgende Scripte / Clients ein:
- API Generator: https://github.com/freifunk/api.freifunk.net/tree/master/generator
- Travis-CI Build Check: https://github.com/freifunk/directory.api.freifunk.net/tree/master/tests
- Community Registry Monitor: http://community-registry.ff-hamm.de/

Bitte helft mit alle bekannten Freifunk-Scripts / -Clients hier zu listen, damit wir bei der Migration keines vergessen.

Bevor sich jemand den Aufwand macht draft-7 Freifunk JSON Schema Dateien zu erstellen, wäre es schon, hierzu vorab Eure Meinung zu bekommen. 

Wie denkt Ihr darüber?

### LINKED ISSUE #152: Draft-3 Freifunk JSON Schema, zwar valide, aber problematisch
Unabhängig wie lange die draft-3 Freifunk JSON Schema noch im Einsatz sein werden, sollte diese nicht nur schematisch valide JSON Schema sein, sondern auch noch unproblematisch in der Handhabung werden.

Egal ob eine Soft-Migration zu draft-7 stattfinden wird (siehe auch https://github.com/freifunk/api.freifunk.net/issues/151) oder wie lange diese dauert, sollten wir die aktuellen draft-3 Freifunk JSON Schema Datei von Usability Problemen befreien. 

**Freifunk draft-3 JSON Schema sind aktuell problematisch**
Unsere Freifunk JSON Schema sind zwar gemäß http://json-schema.org/draft-03/schema# valide JSON Schema Dateien, jedoch sind diese gleichzeitig "empty schema". Was ist das?
Ein "empty schema" ist ein JSON Schema das auf root-ebene keine der folgenden Schema Keywords enthält: https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5
Nicht in der Spezifikation aufgeführte "Schema Keywords" werden ignoriert. Das steht in der Spec vom draft-3 zwar nicht explizit ist aber üblich unter den gängigen Validatoren - oft sogar ohne ein Hinweis auf das etwas ignoriert wurde. In der aktuellen draft-7 Spezifikation ist das Ignorieren aber explizit erwähnt: https://tools.ietf.org/html/draft-handrews-json-schema-01#section-4.3.1, was wirklich gut ist.

Da die Freifunk JSON Schema Dateien auf der root-ebene nur das Keyword "schema" verwenden und dieses nicht zur Spezifikation gehört wird es oft ignoriert und damit auch das eigentliche Freifunk JSON Schema welches sich eine Ebene tiefer befindet. Das führt dazu dass eine Validierung mit diesem JSON Schema zwangsläufig immer erfolgreich verlaufen ("empty schema"; da keine Regeln ausgewertet werden). Oder zumindest in einigen Validatoren anderes.

Einige Freifunk-Scripte (API Generator und o.g. Travis-CI Script) extrahieren daher den Teil unterhalb des "schema"-Feldes und bringen das damit auf root-Ebene. Beispiel:
https://github.com/freifunk/directory.api.freifunk.net/blob/master/tests/test.py#L28

Ein unerfahrener Entwickler oder Anwender aus einer lokalen Gruppe könnte gar nicht bemerkt haben das unser Freifunk JSON Schema einen "wrapper" in sich hat, der es zu einem "empty schema" macht, und alle seine Dateien damit immer als valide ausgibt, obwohl sie es nicht wären, wenn man den "Extract" als JSON Schema verwendet.

Alle Scripte die nicht kurzfristig auf draft-7 umgestellt werden können (z.B. fehlende unterstützung für draft-7) sollten von uns zumindest semantisch-saubere draft-3 Dateien bekommen. Auch hier würde ich diese gerne zunächst Zusätzlich im Repo ablegen um eine **Soft-Migration** bis z.B. **31.12.2019** zu ermöglichen.

(dieses Ticket wird dann für die Commit-Message und den PR verwendet)

Was haltet Ihr davon?

### PR DESCRIPTION
**Pull request by christian-weiss**
resolves #152, resolves #151

### CODE REVIEW

**Comment by christian-weiss** [comment]
@andibraeu please review.

**Comment by christian-weiss** [comment]
@andibraeu please review.

**Comment by andibraeu** [comment]
I have to notes:

The bad one:

The "generator" thing  is still not solved.

The good one:

There's a high probability to get a student involved via Google Summer of Code. The final decision will be made next week. Within the project, the student will take this as a base, evaluate different solutions to create a new generator and update the schema files to the latest json schema draft. And of course, the project also includes to update other tools that use this schema.

**Comment by christian-weiss** [comment]
23 days ago you updated the draft-3 spec files to become draft-7 (no wrapper, no empty schema) files.

Looks like you decided that dependent projects can not follow a soft-migration path, and are forced to do a hard migration.
This makes this PR obsolete. That is why i am closing it now.

**Comment by andibraeu** [comment]
we hope we addressed all tools that used the old schema for validation

**Pull request closed without merging**
